# Use the official Node.js image as a base
FROM node:20-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy the pnpm configuration and package.json files to the working directory
COPY .npmrc pnpm-lock.yaml package.json ./

# Install the dependencies based on the lockfile
RUN pnpm install --frozen-lockfile

# Copy the rest of the application source code to the working directory
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the Next.js application directly
CMD ["pnpm", "run", "dev"]
