services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: demo-docker-nextjs-dev
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: .
          target: ./app
    restart: always
    command: pnpm run dev
