export enum LISTING_EDITOR_SECTION_NAME {
  PHOTO_TOUR = 'Photo tour',
  TITLE = 'Title',
  PROPERTY_TYPE = 'Property Type',
  PRICING = 'Pricing',
  AVAILABILITY = 'Availability',
  NUMBER_OF_GUESTS = 'Number of guests',
  DESCRIPTION = 'Description',
  AMENITIES = 'Amenities',
  ACCESSIBILITY_FEATURES = 'Accessibility features',
  LOCATION = 'Location',
  HOUSE_RULES = 'House rules',
  GUEST_SAFETY = 'Guest safety',
  CANCELLATION_POLICY = 'Cancellation policy',
  COHOSTS = 'CoHosts',
  DIRECTIONS = 'Directions',
  CHECK_IN_METHOD = 'Check-in method',
  WIFI_DETAILS = 'Wifi details',
  CHECKOUT_INSTRUCTIONS = 'Checkout instructions',
  GUIDEBOOKS = 'Guidebooks',
  INTERACTION_PREFERENCES = 'Interaction preferences',
  CHECKIN_CHECKOUT = 'CheckIn-CheckOut',
  CUSTOM_LINK = 'Custom Link',
  ABOUT_HOST = 'About Host',
  BOOKING_SETTINGS = 'Booking settings',
}
